DROP DATABASE IF EXISTS vlyql6y8937cfwbl;
CREATE DATABASE vlyql6y8937cfwbl;

USE vlyql6y8937cfwbl;

SELECT * FROM booklist;

DROP TABLE IF EXISTS booklist;
CREATE TABLE booklist (
	id int NOT NULL AUTO_INCREMENT,
	book_name VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    have_read BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (id)
);